export { default as SollerCases } from "./SollerCases/SollerCases";
export { default as SollerCTA } from "./SollerCTA/SollerCTA";
export { default as SollerFeatures } from "./SollerFeatures/SollerFeatures";
export { default as SollerFooter } from "./SollerFooter/SollerFooter";
export { default as SollerHeader } from "./SollerHeader/SollerHeader";
export { default as SollerPickSun } from "./SollerPickSun/SollerPickSun";
export { default as SollerServices } from "./SollerServices/SollerServices";
export { default as STestimonial } from "./STestimonial/STestimonial";
export { default as TestimonialCard } from "./TestimonialCard/TestimonialCard";
